### ISSUE TITLE
Invalid response from facebook

### ISSUE THREAD

**Issue by zaosoula** [alanzchen/nosedive#1]
Hey after accept Facebook login popup I get this
```
[2017-02-03 18:05:48,035] ERROR in app: Exception on /login/authorized [GET]
Traceback (most recent call last):
  File "/Applications/MAMP/www/nosedive/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Applications/MAMP/www/nosedive/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Applications/MAMP/www/nosedive/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Applications/MAMP/www/nosedive/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Applications/MAMP/www/nosedive/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Applications/MAMP/www/nosedive/venv/lib/python2.7/site-packages/flask_oauth.py", line 429, in decorated
    data = self.handle_oauth2_response()
  File "/Applications/MAMP/www/nosedive/venv/lib/python2.7/site-packages/flask_oauth.py", line 407, in handle_oauth2_response
    type='invalid_response', data=data)
OAuthException: Invalid response from facebook
Invalid response from facebook
```

**Comment by alanzchen** [comment]
It seems that I didn't clean up the unused permissions. Now it should be fixed on the server, can you try again?

I will update the code on GitHub after your confirmation.

Thanks!

**Comment by zaosoula** [comment]
On nosedive.space it's work, but on my local not, after clicking on login in the terminal, I can see 
```
[2017-02-03 18:05:48,035] ERROR in app: Exception on /login/authorized [GET]
Traceback (most recent call last):
  File "/Applications/MAMP/www/nosedive/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Applications/MAMP/www/nosedive/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Applications/MAMP/www/nosedive/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Applications/MAMP/www/nosedive/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Applications/MAMP/www/nosedive/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Applications/MAMP/www/nosedive/venv/lib/python2.7/site-packages/flask_oauth.py", line 429, in decorated
    data = self.handle_oauth2_response()
  File "/Applications/MAMP/www/nosedive/venv/lib/python2.7/site-packages/flask_oauth.py", line 407, in handle_oauth2_response
    type='invalid_response', data=data)
OAuthException: Invalid response from facebook
Invalid response from facebook
```

Can I see the configuration of your Facebook application on the developers panel ?

**Comment by alanzchen** [comment]
See my changes in the commit. You will only need these two permissions.

On Facebook, you will need `user_posts` permission.

Happy hacking :)
